---
# from instructions and q&a at http://kenfallon.com/installing-citrix-on-fedora-21/
- name: get citrix archive
  get_url: >
    url={{citrix_url}}
    dest='/tmp/{{ citrix_archive }}'
    owner=root
    group=root
    mode=644

- name: create landing space for the citrix tar bomb
  file: >
    path='/opt/Citrix'
    state=directory  
    owner="root"
    group="root"
    mode=755

- name: unarchive citrix
  unarchive: >
    copy=no
    src='/tmp/{{ citrix_archive }}'
    dest='/opt/Citrix'

- name: install dependencies
  package: name='{{item}}' state=present
  with_items:
    - gtk2.i686
    - libXext.i686
    - libXrender.i686
    - libXinerama.i686
    - glibc-devel.i686

- name: install necessary certificates
  copy: >
    src='opt/Citrix/ICAClient/keystore/cacerts/{{ item }}'
    dest='/opt/Citrix/ICAClient/keystore/cacerts/{{ item }}'
    owner=root
    group=root
    mode=444
  with_items:
    - 'VeriSignClass3PublicPrimaryCertificationAuthority-G5.pem'
